### ISSUE TITLE
Errors all over the functional_js_syntax code

### ISSUE THREAD

**Issue by jeffcad** [udacity/nd032-c2-functional-programming-with-javascript-starter#1]
Hey Udacity, the code in the functional_js_syntax is full of errors.  I reported on your site in the feedback section, but as I guess I'm not the first one to ever do that, I assume that they aren't being fixed.  If I take the time to fix some of them here and make a pull request, are you going to accept it?  I've seen in another course that there have been students making pull requests to fix errors for months, and nobody has accepted them, leaving the codes full of errors.  I'm willing to help out, but I don't want to waste my time.

Also, the code you provide as the "solutions" in the course are terrible.  A large number of them have errors and do not work.  The last one appears to work at first glance, but it doesn't calculate the average as it claims, and your "expected output" doesn't even notice that.  It is clear that you haven't tried the solutions in that entire section of the course.  Please fix it up, for the sake of future students.  It's the minimum that should be expected of you if you're selling courses.

**Comment by ronny-udacity** [comment]
Thanks for the feedback. We've updated the codes as listed in this [PR](https://github.com/udacity/nd032-c2-functional-programming-with-javascript-starter/pull/5).
